export const Products_base = {
    men: [
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: true,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Футболка поло',
            category: 'men',
            brand: 'Casual Friday by Blend',
            material: 'Шерсть - 50%, Акрил - 50%',
            rating: 4,
            price: 108,
            sizes: ['M INT'],
            discount: '-40%',
            reviews: [
                {
                    name: 'Ivan Kurnov',
                    text: 'Хороший, но оказался большой. Закажем на размер меньше.',
                    rating: 3,
                    id: '620135567d2312f4e7932fc5',
                },
                {
                    name: 'Aliaskei Jurdan',
                    text: 'Отличная Футболка, но мой рост 192 и для меня он короткий. рекомендую для невысоких',
                    rating: 5,
                    id: '620135c87d2312f4e7932fce',
                },
                {
                    name: 'Aliaskei Jurdan',
                    text: 'Отличная Футболка, но мой рост 192 и для меня он короткий. рекомендую для невысоких',
                    rating: 4,
                    id: '620136e17d2312f4e7933007',
                },
                {name: 'Ivan Vorobeynikov', text: 'Норм Футболка', rating: 3, id: '620137a577fffe0cd128be85'},
            ],
            imageURL: require("../src/pages/Men/img/Vodolazka_1.avif"),
            images: [
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/Vodolazka_2.jpg"),
                    id: '62012eeb7d2312f4e7932f0e',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/Vodolazka_3.jpg"),
                    id: '62012eef7d2312f4e7932f12',
                },
            ],
            id: '1',
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Джемпер',
            category: 'men',
            brand: "Levi's",
            material: 'Шерсть - 80%, Полиамид - 20%',
            rating: 5,
            price: 108,
            sizes: ['M INT'],
            discount: null,
            reviews: [],
            imageURL: require("../src/pages/Men/img/Djemper_1_hacks.jpg"),
            images: [
                {
                    color: 'Hacks',
                    url: require("../src/pages/Men/img/Djemper_1_hacks.jpg"),
                    id: '62012fb27d2312f4e7932f1e',
                },
                {
                    color: 'Hacks',
                    url: require("../src/pages/Men/img/Djemper_2_hacks.jpg"),
                    id: '62012fb67d2312f4e7932f21',
                },
                {
                    color: 'Hacks',
                    url: require("../src/pages/Men/img/Djemper_3_hacks.jpg"),
                    id: '62012fba7d2312f4e7932f24',
                },
                {
                    color: 'Hacks',
                    url: require("../src/pages/Men/img/Djemper_4_hacks.jpg"),
                    id: '620130687d2312f4e7932f2d',
                },
                {
                    color: 'Brown',
                    url: require("../src/pages/Men/img/Djemper_1_brown.jpg"),
                    id: '6201306c7d2312f4e7932f30',
                },
                {
                    color: 'Brown',
                    url: require("../src/pages/Men/img/Djemper_2_brown.jpg"),
                    id: '6201306f7d2312f4e7932f33',
                },
                {
                    color: 'Brown',
                    url: require("../src/pages/Men/img/Djemper_3_brown.jpg"),
                    id: '620130a57d2312f4e7932f36',
                },
                {
                    color: 'Brown',
                    url: require("../src/pages/Men/img/Djemper_4_brown.jpg"),
                    id: '620130a97d2312f4e7932f39',
                },
            ],
            id: '2'
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Поло',
            category: 'men',
            brand: 'Auden Cavill',
            material: 'Хлопок - 50%, Полиэстер - 50%',
            rating: 5,
            price: 184.8,
            sizes: ['M INT'],
            discount: null,
            reviews: [],
            imageURL: require("../src/pages/Men/img/Polo_1_hacks.jpg"),
            images: [
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/Polo_1_blue.jpg"),
                    id: '6201311e7d2312f4e7932f3f',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/Polo_2_blue.jpg"),
                    id: '6201311e7d2312f4e7932f3f',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/Polo_3_blue.jpg"),
                    id: '6201311e7d2312f4e7932f3f',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/Polo_4_blue.jpg"),
                    id: '6201311e7d2312f4e7932f3f',
                },
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/Polo_1_white.jpg"),
                    id: '6201314b7d2312f4e7932f4f',
                },
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/Polo_2_white.jpg"),
                    id: '6201314b7d2312f4e7932f4f',
                },
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/Polo_3_white.jpg"),
                    id: '6201314b7d2312f4e7932f4f',
                },
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/Polo_4_white.jpg"),
                    id: '6201314b7d2312f4e7932f4f',
                },
                {
                    color: 'Hacks',
                    url: require("../src/pages/Men/img/Polo_1_hacks.jpg"),
                    id: '6201314f7d2312f4e7932f52',
                },
                {
                    color: 'Hacks',
                    url: require("../src/pages/Men/img/Polo_2_hacks.jpg"),
                    id: '6201314f7d2312f4e7932f52',
                },
                {
                    color: 'Hacks',
                    url: require("../src/pages/Men/img/Polo_3_hacks.jpg"),
                    id: '6201314f7d2312f4e7932f52',
                },
                {
                    color: 'Hacks',
                    url: require("../src/pages/Men/img/Polo_4_hacks.jpg"),
                    id: '6201314f7d2312f4e7932f52',
                },

            ],
            id: '3',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: true,
                isFeatured: false,
            },
            name: 'Кардиган',
            category: 'men',
            brand: 'Primo Emporio',
            material: 'Акрил - 85%, Шерсть - 15%',
            rating: 1,
            price: 148.8,
            sizes: ['M INT'],
            discount: null,
            reviews: [
                {name: 'Alesha Popovich', text: 'Хороший товар!', rating: 1, id: '620134b07d2312f4e7932fa5'}],
            imageURL: require("../src/pages/Men/img/Cardigan_1_black.jpg"),
            images: [
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/Cardigan_1_blue.jpg"),
                    id: '620131f67d2312f4e7932f55',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/Cardigan_2_blue.jpg"),
                    id: '620131fb7d2312f4e7932f58',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/Cardigan_3_blue.jpg"),
                    id: '620131fb7d2312f4e7932f58',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/Cardigan_1_black.jpg"),
                    id: '620132187d2312f4e7932f5b',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/Cardigan_2_black.jpg"),
                    id: '6201321c7d2312f4e7932f5e',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/Cardigan_3_black.jpg"),
                    id: '620132207d2312f4e7932f61',
                },
            ],
            id: '4',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: true,
            },
            name: 'Джемпер CRETA',
            category: 'men',
            brand: 'Mango Man',
            material: 'Хлопок - 100%',
            rating: 4,
            price: 179.99,
            sizes: ['M INT', 'S INT', 'L INT', 'XL INT', 'XXL INT'],
            discount: null,
            reviews: [],
            imageURL: require("../src/pages/Men/img/men_5.jpg"),
            images: [
                {
                    color: 'Multicolor',
                    url: require("../src/pages/Men/img/men_5.jpg"),
                    id: '6203641877fffe0cd128c037',
                },
                {
                    color: 'Multicolor',
                    url: require("../src/pages/Men/img/men_5.jpg"),
                    id: '6203641c77fffe0cd128c03a',
                },
                {
                    color: 'Multicolor',
                    url: require("../src/pages/Men/img/men_5.jpg"),
                    id: '6203642177fffe0cd128c03d',
                },
            ],
            id: 5,
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Джемпер',
            category: 'men',
            brand: 'Jack & Jones',
            material: 'Хлопок - 100%',
            rating: 4,
            price: 134,
            sizes: ['M INT', 'S INT', 'L INT', 'XL INT'],
            discount: null,
            reviews: [
                {
                    name: 'Ruslan Gelik',
                    text: 'Отличный джемпер, сидит прекрасно, современный, хорошего качества.',
                    rating: 5,
                    id: '6203655f77fffe0cd128c058',
                },
                {
                    name: 'Olga',
                    text: 'Размер соответсвует. Мягкий, красивый. Мужу нравится:)',
                    rating: 5,
                    id: '620365cd77fffe0cd128c069',
                },
                {
                    name: 'Fateeva Evgenia',
                    text: 'Рыхлая вязка, по ощущениям быстро могут появиться затяжки. Мужу совсем не понравился "бабушкин" воротник...',
                    rating: 3,
                    id: '620365fb77fffe0cd128c07c',
                },
            ],
            imageURL: require("../src/pages/Men/img/men_6.jpg"),
            images: [
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_6.jpg"),
                    id: '620364e677fffe0cd128c040',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_6.jpg"),
                    id: '620364ea77fffe0cd128c043',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_6.jpg"),
                    id: '620364ee77fffe0cd128c046',
                },
                {
                    color: 'Beige',
                    url: require("../src/pages/Men/img/men_6.jpg"),
                    id: '6203652e77fffe0cd128c049',
                },
                {
                    color: 'Beige',
                    url: require("../src/pages/Men/img/men_6.jpg"),
                    id: '6203653277fffe0cd128c04c',
                },
                {
                    color: 'Beige',
                    url: require("../src/pages/Men/img/men_6.jpg"),
                    id: '6203653677fffe0cd128c04f',
                },
            ],
            id: 6,
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: true,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Кардиган',
            category: 'men',
            brand: 'Stormy Life',
            material: 'Акрил - 80%, Шерсть - 20%',
            rating: 4,
            price: 191.2,
            sizes: ['M INT', 'XXL INT', 'L INT', '3XL INT'],
            discount: null,
            reviews: [
                {
                    name: 'Smirnov Sergey',
                    text: 'Хорошая,немного колючая. Не подошел размер.',
                    rating: 4,
                    id: '62039b5977fffe0cd128c1af',
                },
            ],
            imageURL: require("../src/pages/Men/img/men_7.jpg"),
            images: [
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039ad177fffe0cd128c18b',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039ad577fffe0cd128c18e',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039ad977fffe0cd128c191',
                },
                {
                    color: 'Grey',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039af077fffe0cd128c194',
                },
                {
                    color: 'Grey',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039af377fffe0cd128c197',
                },
                {
                    color: 'Grey',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039af677fffe0cd128c19a',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039b1377fffe0cd128c19d',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039b1777fffe0cd128c1a0',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62039b1b77fffe0cd128c1a3',
                },
            ],
            id: 7,
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Полувер',
            category: 'men',
            brand: 'Tom Tailor',
            material: 'Акрил - 80%, Шерсть - 20%',
            rating: 5,
            price: 64.5,
            sizes: ['S INT', 'M INT', 'XXL INT', 'XL INT'],
            discount: null,
            reviews: [
                {name: 'Dmitry', text: 'Отличный вариант', rating: 5, id: '6203adf977fffe0cd128c1c4'},
                {name: 'Andrey', text: 'Пойдёт :)', rating: 4, id: '6203ae1077fffe0cd128c1cd'},
                {name: 'Nana', text: 'Хороший джемпер,в размер', rating: 4, id: '6203ae2077fffe0cd128c1d8'},
                {
                    name: 'Daniil',
                    text: 'Качество супер, при носке будем надеяться, что покажет себя также',
                    rating: 5,
                    id: '6203ae3177fffe0cd128c1e5',
                },
            ],
            imageURL: require("../src/pages/Men/img/men_8.jpg"),
            images: [
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/men_8.jpg"),
                    id: '6203ad5877fffe0cd128c1bc',
                },
                {
                    color: 'Brown',
                    url: require("../src/pages/Men/img/men_8.jpg"),
                    id: '6203ad6e77fffe0cd128c1bf',
                },
            ],
            id: 8,
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: true,
            },
            name: 'Кардиган',
            category: 'men',
            brand: 'Brave Soul',
            material: 'Хлопок - 65%, Полиэстер - 35%',
            rating: 5,
            price: 59.4,
            sizes: ['S INT', 'M INT', 'XXL INT', 'XL INT'],
            discount: null,
            reviews: [
                {
                    name: 'pok lok',
                    text: "Гарна в'язка і колір. Середня товщина. За свої гроші чудова річ",
                    rating: 5,
                    id: '6203af2977fffe0cd128c1f2',
                },
                {
                    name: 'Olya',
                    text: 'Отлично. Прекрасно сшито, не торчат нитки.',
                    rating: 5,
                    id: '6203af3877fffe0cd128c1f9'
                },
            ],
            imageURL: require("../src/pages/Men/img/men_1.jpg"),
            images: [
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/men_1.jpg"),
                    id: '6203af0c77fffe0cd128c1ee',
                },
            ],
            id: 9,
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Полувер',
            category: 'men',
            brand: 'Tom Tailor',
            material: 'Акрил - 80%, Шерсть - 20%',
            rating: 5,
            price: 74.8,
            sizes: ['S INT', 'M INT', 'XXL INT', 'XL INT'],
            discount: null,
            reviews: [
                {
                    name: 'Olya',
                    text: 'Хороший джемпер, смотрится не дёшево, рекомендую, цвет темнее, чем на фото',
                    rating: 5,
                    id: '6203afec77fffe0cd128c203',
                },
                {name: 'Sergey', text: 'Приятный материал и цвет', rating: 5, id: '6203b00577fffe0cd128c20a'},
            ],
            imageURL: require("../src/pages/Men/img/men_2.jpg"),
            images: [
                {
                    color: 'Turquoise',
                    url: require("../src/pages/Men/img/men_2.jpg"),
                    id: '6203afd477fffe0cd128c1ff',
                },
            ],
            id: 10,
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: true,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: true,
            },
            name: 'Свитер',
            category: 'men',
            brand: 'Dissedent',
            material: 'Полиэстер - 100%',
            rating: 4,
            price: 79.7,
            sizes: ['L INT', 'XXL INT', 'XL INT'],
            discount: '-40%',
            reviews: [
                {name: 'Aliaksei', text: 'Приятный материал и цвет', rating: 5, id: '6204f6c377fffe0cd128c603'},
                {
                    name: 'Smirnov',
                    text: 'Хорошая,немного колючая. Не подошел размер.',
                    rating: 3,
                    id: '6204f6e877fffe0cd128c60c',
                },
            ],
            imageURL: require("../src/pages/Men/img/men_3.jpg"),
            images: [
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/men_3.jpg"),
                    id: '6204f68d77fffe0cd128c5fb',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_3.jpg"),
                    id: '6204f6a777fffe0cd128c5fe',
                },
            ],
            id: 11,
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Водолазка',
            category: 'men',
            brand: 'Jack & Jones',
            material: 'Акрил - 80%, Шерсть - 20%',
            rating: 3,
            price: 93.8,
            sizes: ['M INT', 'XXL INT', '3XL INT', '5XL INT'],
            discount: null,
            reviews: [
                {name: 'Sergey', text: 'Не соответствует размеру.', rating: 2, id: '6204f80b77fffe0cd128c61b'},
                {name: 'Igor', text: 'Качество норм. Маломерка.', rating: 3, id: '6204f81b77fffe0cd128c624'},
            ],
            imageURL: require("../src/pages/Men/img/men_4.jpg"),
            images: [
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_4.jpg"),
                    id: '6204f78577fffe0cd128c613',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/men_4.jpg"),
                    id: '6204f7a177fffe0cd128c616',
                },
            ],
            id: 12,
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: true,
                isBestseller: false,
                isMostViewed: true,
                isFeatured: true
            },
            name: 'Кардиган',
            category: 'men',
            brand: 'Brave Soul',
            material: 'Хлопок - 35%, Полиэстер - 65%',
            rating: 3,
            price: 49.4,
            sizes: ['XXL INT', 'XL INT'],
            discount: null,
            reviews: [
                {
                    name: 'Nikolai',
                    text: 'Супер качество. Красивый и стильный. Акула есть акула!',
                    rating: 3,
                    id: '6204f8fe77fffe0cd128c62f',
                },
            ],
            imageURL: require("../src/pages/Men/img/men_5.jpg"),
            images: [
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/men_5.jpg"),
                    id: '6204f8ea77fffe0cd128c62b',
                },
            ],
            id: 13,
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: true,
            },
            name: 'Джемпер',
            category: 'men',
            brand: 'Produkt',
            material: 'Акрил - 20%, Шерсть - 80%',
            rating: 5,
            price: 134,
            sizes: ['S INT', 'M INT', 'XXL INT', 'XL INT'],
            discount: null,
            reviews: [
                {
                    name: 'Marina',
                    text: 'Свитер отличный. На мужчину ростом 176 см, обычного телосложения, сел хорошо. Очень тёплый, немного колючий.',
                    rating: 4,
                    id: '6204f99777fffe0cd128c63c',
                },
                {name: 'Ilya', text: 'Приятный к телу. Теплый)', rating: 5, id: '6204f9ad77fffe0cd128c645'},
            ],
            imageURL: require("../src/pages/Men/img/men_6.jpg"),
            images: [
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/men_6.jpg"),
                    id: '6204f95a77fffe0cd128c634',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_6.jpg"),
                    id: '6204f97277fffe0cd128c637',
                },
            ],
            id: 14,
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: true
            },
            name: 'Кардиган',
            category: 'men',
            brand: 'Denim Culture',
            material: 'Хлопок - 200%',
            rating: 2,
            price: 261.2,
            sizes: ['S INT', 'M INT', 'L INT', 'XXL INT', 'XL INT'],
            discount: null,
            reviews: [{name: 'Ilya', text: 'Не подошёл по размеру', rating: 2, id: '62050b2a77fffe0cd128c7bd'}],
            imageURL: require("../src/pages/Men/img/men_7.jpg"),
            images: [
                {
                    color: 'White',
                    url: require("../src/pages/Men/img/men_7.jpg"),
                    id: '62050b0e77fffe0cd128c7b9',
                },
            ],
            id: 15,
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: true,
                isFeatured: true,
            },
            name: 'Свитер',
            category: 'men',
            brand: 'Dissedent',
            material: 'Хлопок - 55%, Полиэстер - 45%',
            rating: 2,
            price: 80.4,
            sizes: ['S INT', 'M INT'],
            discount: null,
            reviews: [
                {name: 'Alex', text: 'Плохо сидит не советую', rating: 1, id: '62050bdc77fffe0cd128c7ca'},
                {
                    name: 'Sasha',
                    text: 'На фото сморится красиво,на деле нет.Плохое качество материала,внешний вид,очень сильно маломерит,нужно брать на 2 размера больше своего-54-56,как на 50.Брать не советую!',
                    rating: 2,
                    id: '62050beb77fffe0cd128c7d3',
                },
            ],
            imageURL: require("../src/pages/Men/img/men_8.jpg"),
            images: [
                {
                    color: 'Grey',
                    url: require("../src/pages/Men/img/men_8.jpg"),
                    id: '62050bab77fffe0cd128c7c2',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/men_8.jpg"),
                    id: '62050bc077fffe0cd128c7c5',
                },
            ],
            id: 16,
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: true,
                isFeatured: false,
            },
            name: 'Полувер',
            category: 'men',
            brand: 'Tom Tailor',
            material: 'Акрил - 40%, Шерсть - 60%',
            rating: 5,
            price: 84.8,
            sizes: ['S INT', 'M INT', 'XXL INT', 'XL INT'],
            discount: null,
            reviews: [
                {name: 'Aliaksei', text: 'Очень качественная вещь!', rating: 5, id: '62050d9a77fffe0cd128c7e2'},
                {
                    name: 'Sergey',
                    text: 'Отличный джемпер - прекрасно сел, цвет соответствует фотографии, материал приятный, на голое тело сел комфортно!',
                    rating: 5,
                    id: '62050db077fffe0cd128c7eb',
                },
                {
                    name: 'Liza',
                    text: 'Хороший пуловер. На рост 198 рукава отлично',
                    rating: 5,
                    id: '62050dc277fffe0cd128c7f6',
                },
                {
                    name: 'Natali',
                    text: 'Красивый и качественный свитер, цвет огонь, к телу приятный',
                    rating: 4,
                    id: '62050dd577fffe0cd128c803',
                },
            ],
            imageURL: require("../src/pages/Men/img/men_1.jpg"),
            images: [
                {
                    color: 'Vinous',
                    url: require("../src/pages/Men/img/men_1.jpg"),
                    id: '62050c8b77fffe0cd128c7da',
                },
                {
                    color: 'Beige',
                    url: require("../src/pages/Men/img/men_1.jpg"),
                    id: '62050cab77fffe0cd128c7dd',
                },
            ],
            id: 17,
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: true,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Полувер',
            category: 'men',
            brand: 'Tom Tailor',
            material: 'Акрил - 80%, Шерсть - 20%',
            rating: 4,
            price: 54.8,
            sizes: ['S INT', 'M INT'],
            discount: '-60%',
            reviews: [
                {name: 'Natali', text: 'Ни о чём', rating: 2, id: '620510d177fffe0cd128c814'},
                {name: 'Andrew', text: 'Хорошее качество', rating: 5, id: '620510ed77fffe0cd128c81d'},
            ],
            imageURL: require("../src/pages/Men/img/men_2.jpg"),
            images: [
                {
                    color: 'Yellow',
                    url: require("../src/pages/Men/img/men_2.jpg"),
                    id: '6205107577fffe0cd128c80c',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_2.jpg"),
                    id: '6205109877fffe0cd128c80f',
                },
            ],
            id: '18',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: true,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Полувер',
            category: 'men',
            brand: 'Denim Culture',
            material: 'Хлопок - 50%, Акрил - 50%',
            rating: 4,
            price: 203.4,
            sizes: ['S INT', 'M INT', 'XXL INT', 'XL INT', '3XL INT'],
            discount: '-19%',
            reviews: [
                {
                    name: 'Andrew',
                    text: 'Немного мал, перезаказали на побольше',
                    rating: 4,
                    id: '620511b177fffe0cd128c828'
                },
            ],
            imageURL: require("../src/pages/Men/img/men_3.jpg"),
            images: [
                {
                    color: 'Green',
                    url: require("../src/pages/Men/img/men_3.jpg"),
                    id: '6205117c77fffe0cd128c824',
                },
            ],
            id: '19',
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: true
            },
            name: 'Водолазка',
            category: 'men',
            brand: 'Produkt',
            material: 'Акрил - 50%, Хлопок - 50%',
            rating: 4,
            price: 200.8,
            sizes: ['S INT', 'M INT', 'XXL INT', 'XL INT'],
            discount: null,
            reviews: [
                {
                    name: 'Aliaksei',
                    text: 'Размер чёткий,качество огонь всем советую',
                    rating: 5,
                    id: '6205124477fffe0cd128c890',
                },
                {name: 'Sasha', text: 'Просто хотел водолазку', rating: 5, id: '6205125277fffe0cd128c899'},
                {name: 'Yuri', text: 'Качество не очень', rating: 3, id: '6205126077fffe0cd128c8a4'},
            ],
            imageURL: require("../src/pages/Men/img/men_4.jpg"),
            images: [
                {
                    color: 'Blue',
                    url: require("../src/pages/Men/img/men_4.jpg"),
                    id: '6205121577fffe0cd128c888',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Men/img/men_4.jpg"),
                    id: '6205123177fffe0cd128c88b',
                },
            ],
            id: '20',
        },
    ],
    women: [
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: true,
                isFeatured: false,
            },
            name: 'Платье MARGOT',
            category: 'women',
            brand: 'Mango',
            material: 'Полиэстер - 100%',
            rating: 4,
            price: 99.99,
            sizes: ['L INT', 'XS INT', 'XXS INT', 'S INT', 'M INT'],
            discount: '-58%',
            reviews: [
                {
                    name: 'Anna',
                    text: 'Ткань летящая, расцветка классная, размер соответствует моему 48,его и брала. Мне не подошло, на рост 164 я огромная и в рюшечку)) Стройняшкам, рекомендую',
                    rating: 5,
                    id: '620512f777fffe0cd128c8b0',
                },
                {
                    name: 'Olga',
                    text: 'Красивое платье, очень женственное. Ткань совершенно не мнется, фасон ,я думаю, пойдёт многим. На мой размер 50-52 и рост 170 село идеально. Спасибо.',
                    rating: 5,
                    id: '6205130777fffe0cd128c8b7',
                },
                {
                    name: 'Marina',
                    text: 'А мне хоть тон расцветки и подошёл, но не понравились рюши, резинка на груди...',
                    rating: 3,
                    id: '6205132577fffe0cd128c8c0',
                },
            ],
            images: [
                {
                    color: 'Multicolor',
                    url: require("../src/pages/Women/img/women_1.jpg"),
                    id: '620512e977fffe0cd128c8ac',
                },
            ],
            id: '11214',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: true,
                isBestseller: false,
                isMostViewed: false,
                isFeatured: true,
            },
            name: 'Брюки',
            category: 'women',
            brand: 'Only',
            material: 'Полиэстер - 92%, Эластан - 8%',
            rating: 4,
            price: 105.99,
            sizes: ['36/32 GER', '38/32 GER', '40/32 GET'],
            discount: '-15%',
            reviews: [
                {
                    name: 'BettyTyan',
                    text: 'Сидят классно, но вот материал не особо понравился',
                    rating: 3,
                    id: '620513fd77fffe0cd128c997',
                },
                {
                    name: 'Alexandra',
                    text: 'Посадка оказалась ниже чем предполагалась, и топорщится спереди ткань сильно, так не должно быть',
                    rating: 3,
                    id: '6205141377fffe0cd128c9a0',
                },
                {
                    name: 'Elya',
                    text: 'Просто любоовь. Длина что надо. Правда заказала самые маленькие и мне большеваты в талии, но я просто схуднула недавно, с ремнём норм. Рекомендую',
                    rating: 5,
                    id: '6205142277fffe0cd128c9ab',
                },
            ],
            images: [
                {
                    color: 'Black',
                    url: require("../src/pages/Women/img/women_2.jpg"),
                    id: '620513c677fffe0cd128c98f',
                },
                {
                    color: 'Grey',
                    url: require("../src/pages/Women/img/women_2.jpg"),
                    id: '620513dd77fffe0cd128c992',
                },
            ],
            id: '620126dda5293589353a9c75',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Платье',
            category: 'women',
            brand: "Levi's",
            material: 'Полиэстер - 100%',
            rating: 5,
            price: 289,
            sizes: ['XS INT', 'S INT', 'M INT'],
            discount: null,
            reviews: [],
            images: [
                {
                    color: 'Multicolor',
                    url: require("../src/pages/Women/img/women_3.jpg"),
                    id: '6205147877fffe0cd128c9b3',
                },
            ],
            id: '620126dda5293589353a9c76',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: true,
                isFeatured: true,
            },
            name: 'Купальник',
            category: 'women',
            brand: 'Winzor',
            material: 'Полиамид - 82%, Эластан - 18%',
            rating: 5,
            price: 159,
            sizes: ['40 RUS', '42 RUS', '48 RUS'],
            discount: '-15%',
            reviews: [
                {
                    name: 'omarovs Almira',
                    text: 'не знаю, во всех ли купальниках этого бренда, но я заказывала 2 купальника (оба этого бренда,), оба малы в верхней части, а плавки очень свободные',
                    rating: 5,
                    id: '6205158977fffe0cd128c9be',
                },
                {
                    name: 'Elina',
                    text: 'На не идеальную фигуру) скроет недостатки. В размер',
                    rating: 4,
                    id: '6205159e77fffe0cd128c9c7',
                },
            ],
            images: [
                {
                    color: 'Red',
                    url: require("../src/pages/Women/img/women_4.jpg"),
                    id: '6205155b77fffe0cd128c9b6',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Women/img/women_4.jpg"),
                    id: '6205157277fffe0cd128c9b9',
                },
            ],
            id: '620126dda5293589353a9c77',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: true,
                isBestseller: false,
                isMostViewed: true,
                isFeatured: false,
            },
            name: 'Костюм спортивный',
            category: 'women',
            brand: 'adidas',
            material: 'Полиэстер - 100%',
            rating: 4,
            price: 80.3,
            sizes: ['L INT', 'XS INT', 'S INT'],
            discount: '-60%',
            reviews: [
                {
                    name: 'Gaukhar',
                    text: 'Мой рост 154, S чуток большая в талии (талия 67см), и чуток длинные рукава, но я оставила, так как все было не критично, да и я привыкла к тому что мне все чуток большевато (люди моего роста поймут), не заказывала XS потому что на хотела, чтобы все обтягивало. Мб стоило бы посмотреть, но Sкой я тоже осталась довольна. Качество прекрасное, все красиво село, легкая, приятная на ощупь ткань, выглядит сдержанно и стильно',
                    rating: 5,
                    id: '6205161b77fffe0cd128ca46',
                },
                {
                    name: 'Marina',
                    text: 'Симпатичный костюм. Хорошо сидит на фигуре. К качеству пошива претензий нет. Строчки ровные, нитки не торчат, молнии не заедают. Минус за ткань, к ней все липнет. Все равно выкупила, можно постирать с антистатиком',
                    rating: 4,
                    id: '6205163177fffe0cd128ca4f',
                },
                {
                    name: 'Zhanna',
                    text: 'Костюм просто огонь, на бёдра 120 размер 54/56 как влитой, на рост 170 можно было чуть подлиннее конечно, но все равно супер, посадка не занижена, кофта не короткая, то что надо',
                    rating: 5,
                    id: '6205164e77fffe0cd128ca5a',
                },
                {
                    name: 'Elena',
                    text: 'Отличная классика адидас, брала дочке 11лет на рост 158 худышка размер xs сел впору, но конечно на вырост будет',
                    rating: 5,
                    id: '6205166177fffe0cd128ca67',
                },
                {
                    name: 'Ruzanna',
                    text: 'Классика жанра у адидас. Легкий, теплая осень/весна. Мне не понравилось ощущение на теле из- за состава ткани',
                    rating: 4,
                    id: '6205167777fffe0cd128ca76',
                },
                {
                    name: 'Yana',
                    text: 'Размер в размер, на мой 48 взяла 48-50, к качеству без вопросов. Но на мой рост 176 брюки короткие откровенно',
                    rating: 4,
                    id: '6205168977fffe0cd128ca87',
                },
                {
                    name: 'Yulya',
                    text: 'Хороший костюм. Нужно иметь в виду что брюки не узкие, комфортно свободные. S на 44 свободно',
                    rating: 4,
                    id: '620516a277fffe0cd128ca9a',
                },
                {
                    name: 'Zhenya',
                    text: 'Хороший костюм и вроде бы сел хорошо, но мне напомнил он костюм из 90-х, может сейчас так и модно, но не мой стиль. Размеру заявленному производителем соответсвует.',
                    rating: 3,
                    id: '620516bd77fffe0cd128caaf',
                },
                {
                    name: 'Alla',
                    text: 'На 48/50 и рост 174,брюки короткие,намного выше косточки. Если взять больше размер,в поясе будут широкие.Кофта подошла по размеру. Ткань приятная,пошито качественно. Заказывала В размере L.Советую.',
                    rating: 4,
                    id: '620516db77fffe0cd128cac6',
                },
                {
                    name: 'Irina',
                    text: 'На рост 170 брюки сели хорошо, рукава тоже длинные, б-104, т-73, г-89, размер подошёл, олимпийка без подклада, тоненькая, имейте ввиду, у брюк посадка на 5см ниже талии.',
                    rating: 5,
                    id: '6205170077fffe0cd128cadf',
                },
            ],
            images: [
                {
                    color: 'Black',
                    url: require("../src/pages/Women/img/women_5.jpg"),
                    id: '620515f177fffe0cd128c9ce',
                },
                {
                    color: 'Blue',
                    url: require("../src/pages/Women/img/women_5.jpg"),
                    id: '6205160177fffe0cd128c9d1',
                },
            ],
            id: '620126dda5293589353a9c79',
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Костюм спортивный W TEAMSPORT TS',
            category: 'women',
            brand: 'adidas',
            material: 'Полиэстер - 100%',
            rating: 3,
            price: 143.3,
            sizes: ['L INT', 'XS INT', 'S INT', 'M INT'],
            discount: '-40%',
            reviews: [
                {
                    name: 'Galina',
                    text: 'Не понравился костюм, не успела вернуть . Смотрится колхозно . Качество голимая синтетика.',
                    rating: 1,
                    id: '6205178677fffe0cd128caf6',
                },
                {
                    name: 'Irina',
                    text: 'В целом, нормальный костюм, но , на мой взгляд, ткань тонковата для костюма. Как то несуразно скроены брюки. Для моей фигуры низ брюк очень заужен. Это было бы оправдано, если бы ткань была эластичной ,как ,например , не легинсах, а т.к. это ткань менее эластичная, то есть неудобства при нОске этих брюк. Олимпийка хорошая, удобная, длина до талии. В целом костюм смотрится гармонично, ярко.',
                    rating: 5,
                    id: '6205179d77fffe0cd128cafd',
                },
                {
                    name: 'Inna',
                    text: 'Ткань колится, к телу неприятная, отказ',
                    rating: 2,
                    id: '620517bf77fffe0cd128cb06'
                },
                {
                    name: 'Bazanova',
                    text: 'Очень добротные.На осень,зиму подойдет.Красивый.Люблю эту фирму.Почти всегда в 10.Рекомендую товар.На любой возраст.Только не дамы очень пышных форм.Так как укорочннная кофта.Да и узковатая модель.Всем удачи.',
                    rating: 5,
                    id: '620517d777fffe0cd128cb11',
                },
                {
                    name: 'Anna',
                    text: 'Костюм не понравился, полоски не прямые сужаются к низу из за этого ноги кажутся кривыми. Олимпийка коротковатая на рост 178.',
                    rating: 1,
                    id: '620517ee77fffe0cd128cb1e',
                },
                {
                    name: 'Irina',
                    text: 'Костюм понравился, и размер подошёл, одно но - верх уж слишком короткий. Ориентируясь на рост модели думала что уж мне - то нормально будет, рост у меня 155, но нет, не понравилось как на мне смотрится, к сожалению отказ.',
                    rating: 5,
                    id: '620517ff77fffe0cd128cb2d',
                },
            ],
            images: [
                {
                    color: 'Black',
                    url: require("../src/pages/Women/img/women_6.jpg"),
                    id: '6205176b77fffe0cd128caf1',
                },
            ],
            id: '620126dda5293589353a9c78',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: true,
                isFeatured: false,
            },
            name: 'Куртка утепленная TOKYO',
            category: 'women',
            brand: 'Mango',
            material: 'Полиэстер - 100%',
            rating: 4,
            price: 214,
            sizes: ['XS INT', 'S INT', 'M INT'],
            discount: null,
            reviews: [
                {
                    name: 'Alexandra',
                    text: 'Отлично, большемерит, на 42-44 и рост 160 -выкупила ХС- и рукав впору и длина. В Ске уже был длинный рукав и горб на спине. Тёплая, тяжёленькая.',
                    rating: 5,
                    id: '620518ea77fffe0cd128cb4b',
                },
                {
                    name: 'Darya',
                    text: 'Куртка вообще не понравилась. Неудобный ворот. Если до конца застегнуться молнию, капюшон сразу поднимается, смотрится некрасиво.',
                    rating: 3,
                    id: '620518ff77fffe0cd128cb56',
                },
                {
                    name: 'Anastasia',
                    text: 'Куртка очень удобная, свободного силуэта, довольно плотная - думаю, достаточно тёплая (ещё не проверяла). Эту конкретно не взяла, потому что размер выбрала слишком большой. Выкупила такую же, но чёрную и на размер меньше. Если любите светлые куртки, то к этой однозначно нужно присмотреться.',
                    rating: 5,
                    id: '6205191377fffe0cd128cb63',
                },
            ],
            images: [
                {
                    color: 'Black',
                    url: require("../src/pages/Women/img/women_7.jpg"),
                    id: '6205188a77fffe0cd128cb3e',
                },
                {
                    color: 'Green',
                    url: require("../src/pages/Women/img/women_7.jpg"),
                    id: '620518b077fffe0cd128cb42',
                },
                {
                    color: 'White',
                    url: require("../src/pages/Women/img/women_7.jpg"),
                    id: '620518c277fffe0cd128cb45',
                },
            ],
            id: '620126dda5293589353a9c7d',
        },
        {
            particulars: {
                isNewArrivals: true,
                isSpecial: false,
                isBestseller: false,
                isMostViewed: true,
                isFeatured: false,
            },
            name: 'Джинсы GALYA',
            category: 'women',
            brand: 'Mango',
            material: 'Хлопок - 90%, Переработанный полиэстер - 10%',
            rating: 5,
            price: 139.99,
            sizes: ['32 EUR', '34 EUR', '36 EUR'],
            discount: null,
            reviews: [
                {
                    name: 'Ekaterina',
                    text: 'Наконец-то нашла свои джинсы ! В них не стыдно куда-то пойти, держат форму и к материалу не липнет ничего - идеально.',
                    rating: 5,
                    id: '620519b577fffe0cd128cb74',
                },
                {
                    name: 'Natalia',
                    text: 'Хороший, плотный деним, милым прекрасно. Сняла звёздочку за то, что чёрный-чёрный стал темно-серым после двух стирок без нагрева воды.',
                    rating: 4,
                    id: '620519c477fffe0cd128cb7d',
                },
            ],
            images: [
                {
                    color: 'Black',
                    url: require("../src/pages/Women/img/women_8.jpg"),
                    id: '6205198977fffe0cd128cb6c',
                },
                {
                    color: 'Black',
                    url: require("../src/pages/Women/img/women_8.jpg"),
                    id: '6205199e77fffe0cd128cb6f',
                },
            ],
            id: '620126dda5293589353a9c7b',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: true,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: false,
            },
            name: 'Куртка утепленная',
            category: 'women',
            brand: 'Noisy May',
            material: 'Полиэстер - 100%',
            rating: 4,
            price: 214,
            sizes: ['XS INT', 'S INT', 'M INT'],
            discount: null,
            reviews: [],
            images: [
                {
                    color: 'Brown',
                    url: '/media/620126dda5293589353a9c7c/RTLABB101301_16177596_2_v1.webp',
                    id: '62051ad577fffe0cd128cc0f',
                },
                {
                    color: 'Brown',
                    url: '/media/620126dda5293589353a9c7c/RTLABB101301_16177595_1_v1.webp',
                    id: '62051ad977fffe0cd128cc12',
                },
            ],
            id: '620126dda5293589353a9c7c',
        },
        {
            particulars: {
                isNewArrivals: false,
                isSpecial: false,
                isBestseller: true,
                isMostViewed: false,
                isFeatured: true,
            },
            name: 'Джинсы GALA',
            category: 'women',
            brand: 'Mango',
            material: 'Хлопок - 80%, Переработанный полиэстер - 20%',
            rating: 5,
            price: 139.99,
            sizes: ['32 EUR', '34 EUR', '36 EUR'],
            discount: null,
            reviews: [],
            images: [
                {
                    color: 'Blue',
                    url: '/media/620126dda5293589353a9c7a/RTLABB350001_16215215_2_v1.webp',
                    id: '62051b8177fffe0cd128cf63',
                },
                {
                    color: 'Blue',
                    url: '/media/620126dda5293589353a9c7a/RTLABB350001_16215214_1_v1.webp',
                    id: '62051b8477fffe0cd128cf66',
                },
            ],
            id: '620126dda5293589353a9c7a',
        },
    ],
};
